services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: postilys
    ports:
      - "127.0.0.1:2026:2026"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=2026
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
